/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LibCommon.Network.Types
{
  public enum MessageType
  {
    TestEvent = 0,
  }
}
